# For more information: https://laravel.com/docs/sail
version: '3'
services:
    turno_web:
        image: turno-back
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        networks:
            - sail
        extra_hosts:
            - "laravel.test:127.0.0.1"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sailmysql:/var/lib/mysql'
            - './docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin: 
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - sail
        ports: 
            - 8001:80
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
